apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "local-path-provisioner.fullname" . }}-service-account
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "local-path-provisioner.labels.standard" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "local-path-provisioner.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "local-path-provisioner.labels.standard" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints", "persistentvolumes", "pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "local-path-provisioner.fullname" . }}-bind
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "local-path-provisioner.labels.standard" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "local-path-provisioner.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ template "local-path-provisioner.fullname" . }}-service-account
  namespace: {{ .Release.Namespace }}
