apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  labels:
{{ include "local-path-provisioner.labels.standard" . | indent 4 }}
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
