image:
  # image.registry is the repository where the ActiveMQ Artemis image is stored
  registry: reg-proxy.daxdigital.net
  # image.repository is the ActiveMQ Artemis image name
  repository: server/apache-artemis
  # image.tag is the ActiveMQ Artemis image's tag: https://hub.docker.com/r/vromero/activemq-artemis/tags
  tag: 2.6.4-k8s
  # image.pullPolicy is the ActiveMQ Artemis image's pull policy
  pullPolicy: Always
  # image.pullSecrets optionally specify an array of imagePullSecrets.Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  pullSecrets: []

# artemisUser sets the artemis admin user name
artemisUser: artemis
# artemisPassword sets the artemis admin user password
artemisPassword: simetraehcapa

replicas: 2

# antiAffinity sets an anti affinity policy between masters and slaves as either hard or soft, default is hard
antiAffinity: "soft"

# nameOverride replaces the computed chart name with this given name.
# nameOverride:

# namePrefix sets the prefix for the fullname in the template "global prefix + prefix + name + suffix + global suffix"
# namePrefix:

# nameSuffix sets the suffix for the fullname in the template "global prefix + prefix + name + suffix + global suffix"
# nameSuffix:

global:
# namePrefix sets the global prefix for the fullname in the template "global prefix + prefix + name + suffix + global suffix"
#   namePrefix: Global prefix
# nameSuffix sets the global suffix for the fullname in the template "global prefix + prefix + name + suffix + global suffix"
#   nameSuffix: Global suffix

deployment:
  ## Artemis Deployment annotations
  annotations: {}
  #   name: value
replica:
  ## Artemis Replicas annotations
  annotations: {}
  ## Read more about kube2iam to provide access to s3 https://github.com/jtblin/kube2iam
  #   iam.amazonaws.com/role: role-arn

## Persist data to a persitent volume
persistence:
  testJournalPerformance: AUTO
  enabled: true
  ## If defined, storageClassName: <storageClass>
  ## Default: not set
  ##
  ## storageClass:
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m

## Disable built-in security
## ref: https://activemq.apache.org/artemis/docs/latest/security.html
security:
  enabled: false
  trustStorePassword: xxx
  keyStorePassword: xxx


# A load balander might confuse Minikube when installing with Helm and --wait
# Probably this is only useful for minikube environments and CI
loadbalancer:
  enabled: true
  createInternalOpenStackLoadBalancer: true
