apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coreroller.fullname" . }}
  labels:
{{ include "coreroller.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "coreroller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "coreroller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: COREROLLER_DB_URL
            value: postgres://postgres@127.0.0.1:5432/coreroller?sslmode=disable
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-database
          image: "{{ .Values.database.repository }}:{{ .Values.database.tag }}"
          imagePullPolicy: {{ .Values.database.pullPolicy }}
          volumeMounts:
          - mountPath: /coreroller/data
            name: coreroller-storage
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
      initContainers:
      - name: remove-lost-found
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - rm -rfv /data/lost+found /data/.lock
        volumeMounts:
        - mountPath: /data
          name: coreroller-storage
      volumes:
      - name: coreroller-storage
{{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "coreroller.fullname" .) }}
{{- else }}
        emptyDir: {}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
