apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mid-server.fullname" . }}
  labels:
{{ include "mid-server.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mid-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mid-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if eq .Values.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ template "mid-server.name" . }}
      {{- else if eq .Values.podAntiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ template "mid-server.name" . }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /agent
          name: {{ include "mid-server.fullname" . }}-vol
        env:
        - name: SN_PASSWD
          valueFrom:
            secretKeyRef:
              name: {{ include "mid-server.fullname" . }}
              key: servicenow-password
        - name: SN_URL
          value: {{ .Values.servicenow.url | quote }}
        - name: SN_USER
          value: {{ .Values.servicenow.username | quote }}
        - name: SN_MID_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
          value: {{ .Values.servicenow.name | quote }}
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
        ports:
        - containerPort: {{ .Values.service.port }}
          name: {{ .Values.service.name }}
          protocol: {{ .Values.service.protocol }}
        lifecycle:
          preStop:
            exec:
              command: ["/agent/bin/mid.sh","stop"]
        resources:
          requests:
          {{- if .Values.resources.memory.enabled }}
            memory: {{ .Values.resources.requests.memory }}
          {{- end }}
          {{- if .Values.resources.cpu.enabled }}
            cpu: {{ .Values.resources.requests.cpu }}
          {{- end }}
          limits:
          {{- if .Values.resources.memory.enabled }}
            memory: {{ .Values.resources.limits.memory }}
          {{- end }}
          {{- if .Values.resources.cpu.enabled }}
            cpu: {{ .Values.resources.limits.cpu }}
          {{- end }}
      terminationGracePeriodSeconds: 300
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.persistence.enabled }}
volumeClaimTemplates:
- metadata:
    name: {{ .Values.persistence.existingClaim | default (include "mid-server.fullname" .) }}
  spec:
    accessModes:
    - {{ .Values.persistence.accessMode | quote }}
    {{- if hasKey .Values.persistence "storageClass" }}
      storageClassName: {{ .Values.persistence.storageClass | quote }}
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
    {{- else }}
      volumes:
      - name: {{ include "mid-server.fullname" . }}-vol
        emptyDir: {}
    {{- end }}
