apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mid-server.fullname" . }}
  labels:
{{ include "mid-server.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mid-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mid-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{- if eq .Values.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ template "mid-server.name" . }}
{{- else if eq .Values.podAntiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ template "mid-server.name" . }}
{{- end }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      hostname: {{ .Values.servicenow.name }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /agent
          name: work-vol
        env:
        - name: SN_PASSWD
          valueFrom:
            secretKeyRef:
              name: {{ include "mid-server.fullname" . }}
              key: servicenow-password
        - name: SN_URL
          value: {{ .Values.servicenow.url | quote }}
        - name: SN_USER
          value: {{ .Values.servicenow.username | quote }}
        - name: SN_MID_NAME
          value: {{ .Values.servicenow.name | quote }}
{{- if eq .Values.service.enabled }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: trap-port
          protocol: {{ .Values.service.protocol }}
{{- end }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: work-vol
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "mid-server.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
