apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mid-server.fullname" . }}
  labels:
{{ include "mid-server.labels.standard" . | indent 4 }}
type: Opaque
data:
  servicenow-password: {{ .Values.servicenow.password | b64enc | quote }}
