apiVersion: v1
kind: Service
metadata:
  name: {{ include "mid-server.fullname" . }}
  annotations:
    metallb.universe.tf/allow-shared-ip: snmp
  labels:
{{ include "mid-server.labels.standard" . | indent 4 }}
spec:
  {{if eq .Values.service.type "ClusterIP" }}
  clusterIP: None
  {{end}}
  ports:
    - port: 162
      targetPort: {{ .Values.service.name }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "mid-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
