apiVersion: v1
kind: Service
metadata:
  name: {{ include "mid-server.fullname" . }}
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:{{ include "mid-server.name" . }}:{{ include "mid-server.fullname" . }}"]'
  labels: 
{{ include "mid-server.labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: 42
      targetPort: 42
      protocol: TCP
      name: default
  selector:
    workloadID_eventsystem: "true"
