apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-service.fullname" . }}
  labels:
{{ include "cluster-service.labels" . | indent 4 }}
    kubernetes.io/cluster-service: "false"
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "cluster-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
