apiVersion: v1
kind: Service
metadata:
  name: {{ include "samplicator.fullname" . }}
  labels:
{{ include "samplicator.labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: UDP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "samplicator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
