apiVersion: v1
kind: Service
metadata:
  name: {{ template "local-provisioner.fullname" . }}
  labels:
{{ include "local-provisioner.labels.standard" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "local-provisioner.fullname" . }}
  ports:
  - name: http
    port: 8080
    protocol: TCP
