apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inpli-cred.fullname" . }}
  labels:
{{ include "inpli-cred.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "inpli-cred.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "inpli-cred.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: daxdigital
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SN_BASE_URL
              value: {{ default "" .Values.servicenow.url | quote }}
            - name: DB_HOST
              value: {{ template "inpli-cred.mysql.fullname" . }}
            - name: DB_USERNAME
              value: {{ default "" .Values.mysql.mysqlUser | quote }}
            - name: DB_DATABASE
              value: {{ .Values.mysql.mysqlDatabase | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "inpli-cred.fullname" . }}
                  key: mysql-password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - command: ["/bin/sh", "-c", "for i in $(seq 1 200); do mysql --host=$DB_HOST --port=3306 --user=$DB_USERNAME --password=$DB_PASSWORD --execute \"SHOW DATABASES;\" && exit 0 || sleep 3; done; exit 1"]
          image: imega/mysql-client
          name: {{ include "inpli-cred.fullname" . }}-init-container
          env:
            - name: DB_HOST
              value: {{ template "inpli-cred.mysql.fullname" . }}
            - name: DB_USERNAME
              value: {{ default "" .Values.mysql.mysqlUser | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "inpli-cred.fullname" . }}
                  key: mysql-password
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
