
apiVersion: v1
name: cratedb
version: 0.1.0
description: CrateDB is a distributed SQL database that handles massive amounts of machine data in real-time. This is a Helm chart for CrateDB, to simplify even further its deployment on Kubernetes clusters.
appVersion: 3.2
home: https://crate.io
icon: https://crate.io/wp-content/themes/webflow/images/logo-crate.png
