apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artemis.fullname" . }}-configure-common
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
data:

  template-common.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">
        <name>0.0.0.0</name>
        <cluster-user>exampleUser</cluster-user>
        <cluster-password>secret</cluster-password>
        {{- $name := default .Chart.Name .Values.nameOverride -}}
        {{- $fullname := include "artemis.fullname" . -}}
        {{- $releaseName := printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
        {{- $releaseNamespace := .Release.Namespace -}}
        <acceptors>
          <acceptor name="artemis">tcp://0.0.0.0:61616?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=CORE,AMQP,STOMP,HORNETQ,MQTT,OPENWIRE;useEpoll=true;amqpCredits=1000;amqpLowCredits=300</acceptor>
        </acceptors>
        <connectors>
          {{ range $i,$t := until (int .Values.replicas) }}
              <connector name="{{ $fullname }}-{{ $i }}">tcp://{{ $fullname }}-{{ $i }}.{{ $releaseName }}.{{ $releaseNamespace }}.svc.cluster.local:61616</connector>
          {{end}}
        </connectors>
        <cluster-connections>
          <cluster-connection name="{{ $releaseName }}">
            <address>jms</address>
            <connector-ref>{{ $fullname }}-0</connector-ref>
            <check-period>1000</check-period>
            <connection-ttl>5000</connection-ttl>
            <min-large-message-size>50000</min-large-message-size>
            <call-timeout>30000</call-timeout>
            <retry-interval>500</retry-interval>
            <retry-interval-multiplier>1.0</retry-interval-multiplier>
            <max-retry-interval>5000</max-retry-interval>
            <initial-connect-attempts>-1</initial-connect-attempts>
            <reconnect-attempts>-1</reconnect-attempts>
            <use-duplicate-detection>true</use-duplicate-detection>
            <message-load-balancing>ON_DEMAND</message-load-balancing>
            <max-hops>1</max-hops>
            <confirmation-window-size>32000</confirmation-window-size>
            <call-failover-timeout>30000</call-failover-timeout>
            <notification-interval>1000</notification-interval>
            <notification-attempts>100</notification-attempts>
            <static-connectors>
              {{ range $i,$t := until (int .Values.replicas) }}
                  <connector-ref>{{ $fullname }}-{{ $i }}</connector-ref>
              {{ end }}
            </static-connectors>
         </cluster-connection>
       </cluster-connections>
       <addresses>
        <address name="DLQ">
          <anycast>
            <queue name="DLQ"/>
          </anycast>
        </address>
        <address name="ExpiryQueue">
          <anycast>
            <queue name="ExpiryQueue"/>
          </anycast>
        </address>
        <address name="MonitorEvent">
          <anycast>
            <queue name="MonitorEvent">
              <durable>true</durable>
            </queue>
          </anycast>
        </address>
        <address name="MonitorPerformanceData">
          <anycast>
            <queue name="MonitorPerformanceData">
              <durable>true</durable>
            </queue>
          </anycast>
        </address>
        <address name="ExternalLog">
          <anycast>
            <queue name="ExternalLog">
              <durable>true</durable>
            </queue>
          </anycast>
        </address>
        <address name="Auxillary">
          <anycast>
            <queue name="Auxillary">
              <durable>true</durable>
            </queue>
          </anycast>
        </address>
      </addresses>
      </core>
    </configuration>

  configure-cluster.sh: |

    {{ $name := default .Chart.Name .Values.nameOverride }}
    {{ $releaseName := printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
    set -e
    echo Copying common configuration
    cp /opt/configure-common/template-common.xml /var/lib/artemis/etc-override/broker-10.xml

    echo Setting the connector-ref to ${HOSTNAME}
    xmlstarlet ed -L \
      -N activemq="urn:activemq" \
      -N core="urn:activemq:core" \
      -u "/activemq:configuration/core:core/core:cluster-connections/core:cluster-connection[@name='{{ $releaseName }}']/core:connector-ref" \
      -v "${HOSTNAME}" /var/lib/artemis/etc-override/broker-10.xml

    echo Removing my own connectors - ${HOSTNAME}
    xmlstarlet ed --inplace -N core="urn:activemq:core" \
      -d "//core:cluster-connection/core:static-connectors/core:connector-ref[text()='${HOSTNAME}']" \
      /var/lib/artemis/etc-override/broker-10.xml

    echo setting ${HOSTNAME} as brokername
    xmlstarlet ed -L -N core="urn:activemq:core" -u "//core:name" -v "${HOSTNAME}" \
      /var/lib/artemis/etc-override/broker-10.xml

    if [ "$SECURE" = true ]; then
      echo "Setting ssl specific configuration..."
      list=$(xmlstarlet sel -N core="urn:activemq:core" -t -v "//core:connectors/core:connector/@name" /var/lib/artemis/etc-override/broker-10.xml)
      for i in $list; do
          url=$(xmlstarlet sel -N core="urn:activemq:core" -t -v "//core:connectors/core:connector[@name='$i']" /var/lib/artemis/etc-override/broker-10.xml)
          xmlstarlet ed --inplace -N core="urn:activemq:core" \
            -u "//core:connectors/core:connector[@name='$i']" \
            -v "$url?sslEnabled=true;trustStorePassword=${TRUSTSTORE_PASSWORD};trustStorePath=client.ts;" /var/lib/artemis/etc-override/broker-10.xml
      done
      acceptor=$(xmlstarlet sel -N core="urn:activemq:core" -t -v "//core:acceptors/core:acceptor[@name='artemis']" /var/lib/artemis/etc-override/broker-10.xml)
      xmlstarlet ed --inplace -N core="urn:activemq:core" \
        -u "//core:acceptors/core:acceptor[@name='artemis']" \
        -v "$acceptor;sslEnabled=true;keyStorePassword=${KEYSTORE_PASSWORD};keyStorePath=broker.ks;" /var/lib/artemis/etc-override/broker-10.xml
    fi
