apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
type: Opaque
data:
  artemis-password:  {{ .Values.artemisPassword | b64enc | quote }}
  keystore-password: {{ .Values.security.keyStorePassword | b64enc | quote }}
  truststore-password: {{ .Values.security.trustStorePassword | b64enc | quote }}
