apiVersion: v1
kind: Service
metadata:
  name: {{ include "cratedb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cratedb.name" . }}
    helm.sh/chart: {{ include "cratedb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.adminPort }}
    name: {{ .Values.service.adminName }}
  - port: {{ .Values.service.clusterPort }}
    name: {{ .Values.service.clusterName }}
  - port: {{ .Values.service.postgresPort }}
    name: {{ .Values.service.postgresName }}
  selector:
    app.kubernetes.io/name: {{ include "cratedb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
