apiVersion: v1
kind: Secret
metadata:
  name: {{ template "clair.fullname" . }}
  labels:
{{ include "clair.labels.standard" . | indent 4 }}
type: Opaque
data:
  config.yaml: |-
{{ include (print .Template.BasePath "/_config.yaml.tpl") . | b64enc | indent 4 }}
