apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snmp-proxy.fullname" . }}
  labels:
{{ include "snmp-proxy.labels.standard" . | indent 4 }}
type: Opaque
data:
  trap-community:  {{ .Values.snmptrap.community | b64enc | quote }}
