apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artemis-proxy.fullname" . }}
  labels:
{{ include "artemis-proxy.labels.standard" . | indent 4 }}
type: Opaque
data:
  artemis-password:  {{ .Values.artemisPassword | b64enc | quote }}
  truststore-password: {{ .Values.security.trustStorePassword | b64enc | quote }}
