apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telegraf.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "telegraf.name" . }}
    helm.sh/chart: {{ include "telegraf.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "telegraf.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "telegraf.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - command:
        - /telegraf/fetch_config.py
        env:
          - name: CONFIGS
            value: {{ .Values.collection.configs }}
          - name: LOCATION
            value: {{ .Values.collection.location }}
          - name: COMMUNITY
            valueFrom:
              secretKeyRef:
                key:  community
                name: {{ .Release.Name }}-auth
        image: "{{ .Values.initImage.name }}:{{ .Values.initImage.tag }}"
        imagePullPolicy: Always
        name: telegraf-init
        volumeMounts:
          - mountPath: /telegraf/conf.d
            name: config-vol
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          imagePullSecrets: {{ .Values.image.pullSecrets }}
          env:
            - name: MIDUSER
              value: {{ .Values.collection.miduser }}
            - name: MIDURL
              value: {{ .Values.collection.midurl }}
            - name: MIDPASSWORD
              valueFrom:
                secretKeyRef:
                  key:  midpassword
                  name: {{ .Release.Name }}-auth
          volumeMounts:
            - mountPath: /telegraf/conf.d
              name: config-vol
          resources:
{{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - emptyDir:
          sizeLimit: 1Mi
        name: config-vol
