apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  midpassword: {{ .Values.collection.midpassword | b64enc | quote }}
  community: {{ .Values.collection.community  | b64enc | quote }}
