apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "telegraf.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "telegraf.name" . }}
data:
  # When the config map is mounted as a volume, these will be created as files.
  snmp.conf: |-
    [global_tags]
      # rack = "1a"
      # user = "$USER"
      [agent]
        interval = "$INTERVAL"
        round_interval = true
        metric_batch_size = 1000
        metric_buffer_limit = 10000
        collection_jitter = "0s"
        flush_interval = "10s"
        flush_jitter = "0s"
        precision = ""
        debug = $DEBUG
        quiet = false
        logfile = ""
        hostname = ""
        omit_hostname = false

        # DEBUG....
        #[[outputs.file]]
        #  files = ["stdout"]
        #  data_format = "json"
        # [[inputs.internal]]

        [[outputs.http]]
          ## URL is the address to send metrics to
          url = '$MIDURL'
          ## Timeout for HTTP message
          # timeout = "5s"

          method = "POST"

          ## HTTP Basic Auth credentials
          #username = 'ok-mid-om'
          #password = 'temp123'
          username = '$MIDUSER'
          password = '$MIDPASSWORD'
          data_format = "nowmetric"

            [outputs.http.headers]
              Content-Type = "application/json"
              Accept = "application/json"
