apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Check_MK with a option to specify an ingress
name: checkmk-enterprise
version: 0.1.1
icon: https://mathias-kettner.com/images/apple-touch-icon.png
