apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "checkmk-enterprise.fullname" . }}
  labels:
{{ include "checkmk-enterprise.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "checkmk-enterprise.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "checkmk-enterprise.fullname" . }}
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "checkmk-enterprise.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      affinity:
        {{- if .Values.nodeAffinity.enabled }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.nodeAffinity.label | quote }}
                operator: Exists
        {{- end }}
      {{- if eq .Values.podAntiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: {{ template "checkmk-enterprise.name" . }}
      {{- else if eq .Values.podAntiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ template "checkmk-enterprise.name" . }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      initContainers:
      - name: {{ .Chart.Name }}-init
        command: ["/bin/bash", "/docker-entrypoint-init.sh"]
        env:
        - name: CMK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "checkmk-enterprise.fullname" . }}
              key: checkmk-password
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        volumeMounts:
        - name: storage
          mountPath: /omd/sites
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        ports:
        - containerPort: {{ .Values.service.port | int }}
          name: {{ default "checkmk-enterprise" .Values.service.nameOverride }}-http
        livenessProbe:
          httpGet:
            path: /
            port: {{ default "checkmk-enterprise" .Values.service.nameOverride }}-http
        readinessProbe:
          httpGet:
            path: /
            port: {{ default "checkmk-enterprise" .Values.service.nameOverride }}-http
        volumeMounts:
          - mountPath: /omd/sites
            name: storage
        env:
        - name: CMK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "checkmk-enterprise.fullname" . }}
              key: checkmk-password
        - name: AUTOMATION_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "checkmk-enterprise.fullname" . }}
              key: checkmk-automation-secret
        - name: SNOW_MID_PASSWD
          valueFrom:
            secretKeyRef:
              name: {{ include "checkmk-enterprise.fullname" . }}
              key: servicenow-password
        - name: DEFAULT_SNMP_COMMUNITY
          valueFrom:
            secretKeyRef:
              name: {{ include "checkmk-enterprise.fullname" . }}
              key: checkmk-default-snmp-community
        - name: SNOW_MID_URL
          value: {{ .Values.servicenow.url | quote }}
        - name: SNOW_MID_USER
          value: {{ .Values.servicenow.username | quote }}
        resources:
          requests:
          {{- if .Values.resources.memory.enabled }}
            memory: {{ .Values.resources.requests.memory }}
          {{- end }}
          {{- if .Values.resources.cpu.enabled }}
            cpu: {{ .Values.resources.requests.cpu }}
          {{- end }}
          limits:
          {{- if .Values.resources.memory.enabled }}
            memory: {{ .Values.resources.limits.memory }}
          {{- end }}
          {{- if .Values.resources.cpu.enabled }}
            cpu: {{ .Values.resources.limits.cpu }}
          {{- end }}
      terminationGracePeriodSeconds: 0
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if not .Values.persistence.enabled }}
      volumes:
      - name: storage
        emptyDir: {}
    {{- end }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - {{ .Values.persistence.accessMode | quote }}
        {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
  {{- end }}
