apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkmk-enterprise.fullname" . }}
  labels:
    kubernetes.io/cluster-service: "true"
{{ include "checkmk-enterprise.labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "checkmk-enterprise.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
