apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkmk-enterprise.fullname" . }}
  labels:
    {{- if not .Values.ingress.enabled }}
    kubernetes.io/cluster-service: "true"
    {{- end }}
{{ include "checkmk-enterprise.labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "checkmk-enterprise.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 5000
  publishNotReadyAddresses: true
