apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: {{ .Values.rook.poolName }}
  labels:
{{ include "rook-ceph-cluster.labels.standard" . | indent 4 }}
spec:
  failureDomain: host
  replicated:
    size: {{ .Values.cluster.pool.replicated }}
