#################################################################################
# The Ceph Cluster CRD example
#################################################################################
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "rook-ceph-cluster.labels.standard" . | indent 4 }}
spec:
  cephVersion:
    # For the latest ceph images, see https://hub.docker.com/r/ceph/ceph/tags
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    allowUnsupported: true
  dataDirHostPath: /var/lib/rook
  serviceAccount: rook-ceph-cluster
  dashboard:
    enabled: true
    ssl: false
  mon:
    count: 3
    allowMultiplePerNode: true
  storage:
    useAllNodes: {{ .Values.cluster.storage.useAllNodes }}
    useAllDevices: true
{{- if not .Values.cluster.storage.useAllNodes }}
    deviceFilter: {{ .Values.cluster.storage.deviceFilter | quote }}
{{- end }}
    config:
      databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "1" # this value can be overridden at the node or device level
    directories:
    - path: {{ .Values.cluster.storage.directory | quote }}
 {{- if not .Values.cluster.storage.useAllNodes }}
    nodes:
 {{- range $index, $node := .Values.cluster.storage.nodes }}
    - name: {{ $node.name | quote }}
  {{- if $node.deviceFilter | quote }}
      deviceFilter: {{ $node.deviceFilter }}
  {{- end }}
 {{- end }}
 {{- end }}
