apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.rbdStorageClassName }}
  labels:
{{ include "rook-ceph-cluster.labels.standard" . | indent 4 }}
provisioner: ceph.rook.io/block
parameters:
  blockPool: {{ .Values.rook.poolName }}
  # The value of "clusterNamespace" MUST be the same as the one in which your rook cluster exist
  clusterName: {{ .Release.Namespace }}
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  # fstype: xfs
# Optional, default reclaimPolicy is "Delete". Other options are: "Retain", "Recycle" as documented in https://kubernetes.io/docs/concepts/storage/storage-classes/
reclaimPolicy: {{ .Values.cluster.storage.retainPolicy }}
