kind: ConfigMap
apiVersion: v1
metadata:
  labels:
{{ include "gitea.labels.standard" . | indent 4 }}
  name: {{ template "gitea.gitea.fullname" . }}-config
data:
  app.ini: |-
    APP_NAME = {{ .Values.service.gitea.appName }}
    RUN_MODE = {{ .Values.service.gitea.runMode }}

    [repository.upload]
    ENABLED = {{ .Values.service.gitea.repositoryUploadEnabled }}
    ALLOWED_TYPES = {{ .Values.service.gitea.repositoryUploadAllowedTypes }}
    MAX_FILE_SIZE = {{ .Values.service.gitea.repositoryUploadMaxFileSize }}
    MAX_FILES = {{ .Values.service.gitea.repositoryUploadMaxFiles }}

    [server]
    PROTOCOL = http
    DOMAIN = {{ .Values.service.gitea.serverDomain }}
    ROOT_URL = {{ .Values.service.gitea.serverRootUrl }}
    LANDING_PAGE = {{ .Values.service.gitea.serverLandingPage }}
    SSH_DOMAIN = {{ default .Values.service.gitea.serverDomain .Values.service.sshDomain }}
    SSH_PORT = {{ .Values.service.sshPort }}
    SSH_LISTEN_PORT = {{ .Values.service.sshPort }}
    LFS_START_SERVER = false

    [service]
    ENABLE_CAPTCHA = {{ .Values.service.gitea.serviceEnableCaptcha }}
    ACTIVE_CODE_LIVE_MINUTES = 180
    RESET_PASSWD_CODE_LIVE_MINUTES = 180
    REGISTER_EMAIL_CONFIRM = {{ .Values.service.gitea.serviceRegisterEmailConfirm }}
    DISABLE_REGISTRATION = {{ .Values.service.gitea.serviceDisableRegistration }}
    REQUIRE_SIGNIN_VIEW = {{ .Values.service.gitea.serviceRequireSignInView }}
    ENABLE_NOTIFY_MAIL = {{ .Values.service.gitea.serviceEnableNotifyMail }}
    ENABLE_REVERSE_PROXY_AUTHENTICATION = false
    ENABLE_REVERSE_PROXY_AUTO_REGISTRATION = false

    [mailer]
    ENABLED = {{ .Values.service.gitea.mailerEnabled }}
    HOST = {{ .Values.service.gitea.mailerHost }}
    DISABLE_HELO = false
    HELO_HOSTNAME =
    SKIP_VERIFY = {{ .Values.service.gitea.mailerSkipVerify }}
    SUBJECT_PREFIX = {{ .Values.service.gitea.mailerSubjectPrefix }}
    FROM = {{ .Values.service.gitea.mailerFrom }}
    USER = {{ .Values.service.gitea.mailerUser }}
    PASSWD = {{ .Values.service.gitea.mailerPasswd }}
    USE_PLAIN_TEXT = text/plain

    [database]
    DB_TYPE = {{ .Values.service.gitea.databaseType | quote }}
    HOST = {{ template "gitea.database.host" . }}
    NAME = {{ template "gitea.database.name" . }}
    USER = {{ template "gitea.database.user" . }}
    PASSWD = {{ template "gitea.database.password" . }}

    [security]
    INSTALL_LOCK = {{ .Values.service.gitea.installLock }}
    SECRET_KEY = {{ default "" .Values.service.gitea.securitySecretKey | b64enc | quote }}

    [ui]
    EXPLORE_PAGING_NUM = {{ .Values.service.gitea.uiExplorePagingNum }}
    ISSUE_PAGING_NUM = {{ .Values.service.gitea.uiIssuePagingNum }}
    FEED_MAX_COMMIT_NUM = {{ .Values.service.gitea.uiFeedMaxCommitNum }}

    [cache]
    ADAPTER = {{ .Values.service.gitea.cacheAdapter }}
    INTERVAL = {{ .Values.service.gitea.cacheInterval }}
    HOST = {{ .Values.service.gitea.cacheHost }}

    [webhook]
    QUEUE_LENGTH = {{ .Values.service.gitea.webhookQueueLength }}
    DELIVER_TIMEOUT = {{ .Values.service.gitea.webhookDeliverTimeout }}
    SKIP_TLS_VERIFY = {{ .Values.service.gitea.webhookSkipTlsVerify }}
    PAGING_NUM = {{ .Values.service.gitea.webhookPagingNum }}

    [log]
    MODE = {{ .Values.service.gitea.logMode }}
    LEVEL = {{ .Values.service.gitea.logLevel }}

    [cron]
    ENABLED = {{ .Values.service.gitea.cronEnabled }}
    RUN_AT_START = {{ .Values.service.gitea.cronRunAtStart }}

    [cron.update_mirrors]
    SCHEDULE = {{ .Values.service.gitea.cronUpdateMirrorsSchedule }}

    [cron.repo_health_check]
    SCHEDULE = {{ .Values.service.gitea.cronRepoHealthCheckSchedule }}
    TIMEOUT = {{ .Values.service.gitea.cronRepoHealthCheckTimeout }}
    ARGS = {{ .Values.service.gitea.cronRepoHealthCheckArgs }}

    [cron.check_repo_stats]
    RUN_AT_START = {{ .Values.service.gitea.cronCheckRepoStatsRunAtStart }}
    SCHEDULE = {{ .Values.service.gitea.cronCheckRepoStatsSchedule }}

    [cron.repo_archive_cleanup]
    RUN_AT_START = {{ .Values.service.gitea.cronRepoArchiveCleanupRunAtStart }}
    SCHEDULE = {{ .Values.service.gitea.cronRepoArchiveCleanupSchedule }}
    OLDER_THAN = {{ .Values.service.gitea.cronRepoArchiveCleanupOlderThan }}

    [other]
    SHOW_FOOTER_BRANDING = {{ .Values.service.gitea.otherShowFooterBranding }}
    SHOW_FOOTER_VERSION = {{ .Values.service.gitea.otherShowFooterVersion }}
    SHOW_FOOTER_TEMPLATE_LOAD_TIME = {{ .Values.service.gitea.otherShowFooterTemplateLoadTime }}
