{{- if .Values.service.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $serviceName := default "gitea" .Values.service.nameOverride -}}
{{- $httpPort := .Values.service.httpPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "gitea.gitea.fullname" . }}
  labels:
{{ include "gitea.labels.standard" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.service.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.service.gitea.serverDomain }}
      http:
        paths:
        - backend:
            serviceName: {{ printf "%s-%s" $releaseName $serviceName | trunc 63 | trimSuffix "-" }}
            servicePort: {{ $httpPort }}
{{- if .Values.service.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.service.gitea.serverDomain }}
  {{- if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
{{- end -}}
{{- end -}}
