
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitea.gitea.fullname" . }}
  labels:
{{ include "gitea.labels.standard" . | indent 4 }}
type: Opaque
data:
  postgresql-user: {{ .Values.postgresql.postgresUser | b64enc | quote }}
