apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitea.fullname" . }}
  labels:
{{ include "gitea.labels.standard" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.service.httpPort | int }}
    targetPort: 3000
{{- if (and (eq .Values.serviceType "NodePort") (not (empty .Values.service.httpNodePort))) }}
    nodePort: {{ .Values.service.httpNodePort | int }}
{{- end }}
    name: {{ default "gitea" .Values.service.nameOverride }}-http
{{- if .Values.service.sshEnable }}
  - port: {{ .Values.service.sshPort | int }}
    targetPort: 22
{{- if (and (eq .Values.serviceType "NodePort") (not (empty .Values.service.sshNodePort))) }}
    nodePort: {{ .Values.service.sshNodePort | int }}
{{- end }}
    name: {{ default "gitea" .Values.service.nameOverride }}-ssh
{{- end }}
  selector:
    app: {{ template "gitea.fullname" . }}
