apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitea.fullname" . }}
  labels:
{{ include "gitea.labels.standard" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: {{ default "gitea" .Values.service.nameOverride }}-http
      port: {{ .Values.service.httpPort | int }}
      targetPort: {{ default "gitea" .Values.service.nameOverride }}-http
{{- if not .Values.service.sshDisable }}
    - name: {{ default "gitea" .Values.service.nameOverride }}-ssh
      port: {{ .Values.service.sshPort | int }}
      targetPort: {{ default "gitea" .Values.service.nameOverride }}-ssh
{{- end }}
  selector:
    app: {{ template "gitea.fullname" . }}
